li =[]
print(f' li containts {len(li)} elements')
li.append(10)
print(f' li containts {len(li)} elements')
li.insert(1,98)
print(f' li containts {len(li)} elements')
li.append(144)
li.append(677)
li.append(444)
print(f' li containts {len(li)} elements')
print(li)
print(f'{li.pop()} is deleted element is')
print('list  after deleting the element')
print(li)
li.remove(98)
print(li,'iiiiiiiiiii')
x = li.__add__([999,444,333])
print(li)
print('x = ',x)