# t =(10,29,30,40,50)
# print(t[-1],t[4])
# print(t[-2],t[3])
# print(t[-3],t[2])
# print(t[-4],t[1])
# print(t[-5],t[0])
# print('Displying tuple elements using +ve index')
t =(10,10,30,40)
print(t)
print(t*3) # multiplicatio operator same elements repeates again and again based on the given number
print(t)
